# Generated by Django 4.1.3 on 2022-12-09 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('profile_picture', models.ImageField(unique=True, upload_to='productImage/')),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Smart Phones', 'Smart Phones'), ('Electronics', 'Electronics'), ('Electrical Tools', 'Electrical Tools'), ('Cars', 'Cars'), ('Motor Bikes', 'Motor Bikes')], default=None, max_length=20)),
                ('approved', models.CharField(default='Unapproved', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
