# Generated by Django 4.1.3 on 2022-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='approved',
            field=models.CharField(default='Upa', max_length=10, null=True),
        ),
    ]
