# Generated by Django 4.1.3 on 2022-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_table_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='product_table',
            name='product_picture',
            field=models.ImageField(null=True, unique=True, upload_to='productImage/'),
        ),
    ]
