# Generated by Django 4.1.3 on 2022-11-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('date_of_birth', models.CharField(max_length=11, null=True)),
                ('gender', models.CharField(max_length=11, null=True)),
                ('nationality', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('United Kingdom', 'UK'), ('USA', 'USA')], max_length=50, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Abia', 'Abia'), ('Abia', 'Abia'), ('Abia', 'Abia'), ('Abia', 'Abia'), ('Abia', 'Abia'), ('Abia', 'Abia')], max_length=50, null=True)),
                ('means_of_identity', models.ImageField(null=True, upload_to='identityImage/')),
                ('particulars', models.FileField(null=True, upload_to='particularsImage//')),
                ('profile_passport', models.FileField(null=True, upload_to='staffImage/')),
                ('position', models.FileField(choices=[('MD', 'MD'), ('CEO', 'CEO'), ('HOD', 'HOD'), ('Accountant', 'Accountant'), ('Secretary', 'Secretary'), ('Admin', 'Admin'), ('Clerical officer', 'Clerical officer'), ('Technician', 'Technician'), ('Sales officer', 'Sales officer'), ('Marketing', 'Marketing'), ('HR', 'HR')], max_length=50, null=True, upload_to='')),
                ('department', models.CharField(choices=[('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Admin', 'Admin'), ('Production', 'Production'), ('Accounting', 'Accounting'), ('Electrical', 'Electrical')], max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce'), ('Complicate', 'Complicate')], max_length=20, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('next_of_kin', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
