# Generated by Django 4.1.3 on 2022-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('On Leave', 'On Leave'), ('Retired', 'Retired'), ('Resigned', 'Resigned')], default='Active', max_length=50, null=True),
        ),
    ]
